import type { Metadata, Viewport } from "next";
import {
  UnifrakturMaguntia,
  Libre_Caslon_Display,
  Libre_Caslon_Text,
  Libre_Franklin,
} from "next/font/google";
import "./globals.css";
import { siteOrigin } from "@/lib/site";
import PaperTexture from "@/components/PaperTexture";
import ServiceWorker from "@/components/ServiceWorker";
import { AccountProvider } from "@/components/Account";
import { PreferencesProvider } from "@/components/Preferences";
import Onboarding from "@/components/Onboarding";

/** Nameplate. Blackletter, as on the Times, the Telegraph and the Tribune. */
const mast = UnifrakturMaguntia({
  variable: "--font-mast",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

/** Display cut of Caslon, for headlines set large. */
const head = Libre_Caslon_Display({
  variable: "--font-head",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

/** Text cut of the same family, for body copy and smaller headlines. */
const body = Libre_Caslon_Text({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

/** Franklin Gothic revival — the American newspaper sans, for furniture. */
const label = Libre_Franklin({
  variable: "--font-label",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

/** The paper's own words, written once and shared with the social cards. */
const TITLE = "The AI Daily — Two Cents Edition";
const DESCRIPTION =
  "One edition a day. Everything that mattered in artificial intelligence, deduplicated and set in type.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  applicationName: "The AI Daily",
  manifest: "/manifest.webmanifest",
  /**
   * Every URL-shaped field below this line is written relative and composed
   * against this. Without it a relative `openGraph.images` is a build error,
   * and the OG images are generated by the file convention rather than typed
   * out — so the base has to be right before there is anything to resolve.
   *
   * Shared with app/sitemap.ts and app/robots.ts, which resolve the same
   * origin from the same environment; see the note there on why it is the
   * production hostname and not the per-deployment one.
   */
  metadataBase: new URL(siteOrigin()),
  /**
   * The link preview, which until now was a bare grey rectangle.
   *
   * `images` is absent on purpose, here and on every page below: the
   * `opengraph-image` file convention fills that field in, and the docs are
   * explicit that file-based metadata outranks this object. Writing image URLs
   * here would be a second, hand-maintained copy of an answer the framework
   * already knows.
   *
   * Worth knowing when editing the pages: Next merges `openGraph` shallowly,
   * so a page that declares its own block replaces this one whole rather than
   * adding to it. That is why `siteName` and `locale` are repeated on the
   * story, section and briefing pages — without them a shared story link
   * loses the name of the paper it came from.
   */
  openGraph: {
    type: "website",
    siteName: "The AI Daily",
    // en_GB to match the paper: lib/digest.ts sets the dateline with the
    // en-GB formatter, and the bulletin says "Wednesday the sixteenth of
    // September" rather than "September sixteenth".
    locale: "en_GB",
    title: TITLE,
    description: DESCRIPTION,
    url: "/",
  },
  twitter: {
    // The paper is a broadsheet; a 1200x630 card shows the masthead, where
    // `summary` crops it to a thumbnail beside the text.
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
  // iOS ignores the web manifest and reads these instead.
  appleWebApp: {
    capable: true,
    title: "AI Daily",
    statusBarStyle: "default",
  },
  icons: {
    icon: "/icons/icon-192.png",
    apple: "/icons/apple-touch-icon.png",
  },
};

export const viewport: Viewport = {
  // Matches the ink, so the status bar reads as part of the masthead.
  themeColor: "#2b1f12",
  // Lets the paper run under the notch rather than being letterboxed by it.
  viewportFit: "cover",
  width: "device-width",
  initialScale: 1,
};

const themeInit = `
try {
  if (localStorage.getItem('edition') === 'night') {
    document.documentElement.classList.add('night');
  }
} catch (e) {}
`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${mast.variable} ${head.variable} ${body.variable} ${label.variable} h-full`}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInit }} />
      </head>
      <body className="min-h-full">
        <PaperTexture />
        {/* Account first: preferences need to know who is signed in before
            they can decide whether to sync. */}
        <AccountProvider>
          <PreferencesProvider>
            {children}
            <Onboarding />
          </PreferencesProvider>
        </AccountProvider>
        <ServiceWorker />
      </body>
    </html>
  );
}
