/**
 * The wire.
 *
 * There is no backend to talk to. The web app bakes the whole edition into one
 * static JSON document at build time and Vercel's CDN serves it as a file —
 * `force-static`, no function invocation, CORS open to anyone. So this client
 * reads exactly what a browser reads, costs the project nothing per install,
 * and needs no key.
 *
 * The types below were written against the live response, not the documented
 * shape. Two things were only true in the real payload and would have been
 * wrong if guessed:
 *
 *  - `story.url` is `/story/<id>`, a path on the web app, not a link to the
 *    publisher. The outbound link to the original reporting is in
 *    `story.sources[].url`.
 *  - `story.brief` is `null` on every story in the edition as published. The
 *    field is real and the web app can fill it, but a client that assumed an
 *    object there would crash on today's paper.
 */

const EDITION_URL = "https://ai-daily-umber.vercel.app/api/edition";

/**
 * A phone on a train has no error page to show, so a hung socket must not hang
 * the app. Ten seconds is long enough for a slow cell connection to deliver
 * 57KB and short enough that the reader is not left staring at a spinner
 * before we fall back to what is already on the device.
 */
const TIMEOUT_MS = 10_000;

export type Source = {
  name: string;
  url: string;
  publishedAt: string;
};

/**
 * Model-written material, kept separate from the reporting.
 *
 * `provenance` is the field that decides how this may be displayed, and the
 * payload's own notice is explicit that neither kind is original reporting.
 * Nothing in here may reach the screen without that label attached.
 */
export type Brief = {
  provenance: "compiled-from-sources" | "machine-written";
  method: string;
  tldr: string | null;
  keyPoints: string[];
  whyItMatters: string | null;
  whoIsAffected: string | null;
};

export type Story = {
  id: string;
  headline: string;
  deck: string;
  /** Publisher-written standfirsts, one per outlet. Never model output. */
  body: string[];
  section: string;
  publishedAt: string;
  /** Distinct outlets that carried it. What the tally marks count. */
  sourceCount: number;
  sources: Source[];
  /** A path on the web app, e.g. `/story/abc123` — not the publisher's link. */
  url: string;
  brief: Brief | null;
};

export type Edition = {
  edition: {
    number: number;
    date: string;
    itemsIngested: number;
    eventsPublished: number;
  };
  sections: { section: string; count: number }[];
  publishers: string[];
  stories: Story[];
  notice: string;
};

/* ------------------------------------------------------------------ *
 * Coercion
 * ------------------------------------------------------------------ */

/*
 * Everything below treats the response as untrusted.
 *
 * Not because the endpoint is hostile — it is the same project — but because
 * this app ships to app stores and the edition it reads is regenerated by a
 * scheduled job every morning, without the app being rebuilt or reviewed. A
 * field that changes shape upstream must degrade to a missing byline, never to
 * a white screen on a version of the app we can no longer change. The same
 * coercion also runs over whatever was cached on disk, which may have been
 * written by an older build.
 */

const str = (v: unknown, fallback = ""): string =>
  typeof v === "string" ? v : fallback;

const num = (v: unknown, fallback = 0): number =>
  typeof v === "number" && Number.isFinite(v) ? v : fallback;

const strings = (v: unknown): string[] =>
  Array.isArray(v) ? v.filter((x): x is string => typeof x === "string") : [];

function coerceSource(raw: unknown): Source | null {
  if (!raw || typeof raw !== "object") return null;
  const o = raw as Record<string, unknown>;
  const name = str(o.name);
  // An outlet with no name cannot be credited, and crediting it as "" would
  // print an empty row in the list of who reported the story.
  if (!name) return null;
  return { name, url: str(o.url), publishedAt: str(o.publishedAt) };
}

function coerceBrief(raw: unknown): Brief | null {
  if (!raw || typeof raw !== "object") return null;
  const o = raw as Record<string, unknown>;
  // Unlabelled generated text is the one thing this app must not render, so an
  // unrecognised provenance drops the brief entirely rather than guessing.
  const provenance = o.provenance;
  if (provenance !== "compiled-from-sources" && provenance !== "machine-written") {
    return null;
  }
  return {
    provenance,
    method: str(o.method, "unknown"),
    tldr: typeof o.tldr === "string" ? o.tldr : null,
    keyPoints: strings(o.keyPoints),
    whyItMatters: typeof o.whyItMatters === "string" ? o.whyItMatters : null,
    whoIsAffected: typeof o.whoIsAffected === "string" ? o.whoIsAffected : null,
  };
}

function coerceStory(raw: unknown): Story | null {
  if (!raw || typeof raw !== "object") return null;
  const o = raw as Record<string, unknown>;

  const id = str(o.id);
  const headline = str(o.headline);
  // Without an id there is nothing to route to, and without a headline there is
  // nothing to print. Anything else can be missing and still make a page.
  if (!id || !headline) return null;

  const sources = Array.isArray(o.sources)
    ? o.sources.map(coerceSource).filter((s): s is Source => s !== null)
    : [];

  const body = strings(o.body);
  const deck = str(o.deck);

  return {
    id,
    headline,
    deck,
    // The story screen prints the body; falling back to the deck keeps it from
    // being a headline over blank paper.
    body: body.length > 0 ? body : deck ? [deck] : [],
    section: str(o.section, "The wire"),
    publishedAt: str(o.publishedAt),
    // Trust the field, but never print fewer marks than there are outlets
    // listed underneath them. In the live edition these disagree on two of
    // fifty-four stories: `sourceCount` counts distinct publisher names while
    // `sources` is deduplicated by internal source id, so a publisher filing
    // under two feed ids appears twice in the list and once in the count.
    sourceCount: Math.max(num(o.sourceCount), sources.length),
    sources,
    url: str(o.url),
    brief: coerceBrief(o.brief),
  };
}

export function coerceEdition(raw: unknown): Edition | null {
  if (!raw || typeof raw !== "object") return null;
  const o = raw as Record<string, unknown>;

  const stories = Array.isArray(o.stories)
    ? o.stories.map(coerceStory).filter((s): s is Story => s !== null)
    : [];

  // An edition with no stories is not a paper. Returning null here sends the
  // caller to the cache, which is the right move for a truncated response.
  if (stories.length === 0) return null;

  const ed = (o.edition ?? {}) as Record<string, unknown>;

  const sections = Array.isArray(o.sections)
    ? o.sections
        .map((s) => {
          if (!s || typeof s !== "object") return null;
          const c = s as Record<string, unknown>;
          const section = str(c.section);
          return section ? { section, count: num(c.count) } : null;
        })
        .filter((s): s is { section: string; count: number } => s !== null)
    : [];

  return {
    edition: {
      number: num(ed.number),
      date: str(ed.date),
      itemsIngested: num(ed.itemsIngested),
      eventsPublished: num(ed.eventsPublished, stories.length),
    },
    // Derive the desk index if the server ever stops sending one; browsing by
    // section is a whole screen and it should not go blank over a missing field.
    sections: sections.length > 0 ? sections : deriveSections(stories),
    publishers: strings(o.publishers),
    stories,
    notice: str(o.notice),
  };
}

function deriveSections(stories: Story[]): { section: string; count: number }[] {
  const counts = new Map<string, number>();
  for (const s of stories) counts.set(s.section, (counts.get(s.section) ?? 0) + 1);
  return [...counts.entries()]
    .map(([section, count]) => ({ section, count }))
    .sort((a, b) => b.count - a.count);
}

/* ------------------------------------------------------------------ *
 * Fetching
 * ------------------------------------------------------------------ */

export class WireError extends Error {}

export async function fetchEdition(): Promise<Edition> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);

  try {
    /*
     * No request headers, deliberately.
     *
     * This asked for `cache-control: no-cache` to force a trip to the network
     * on refresh. That header is not CORS-safelisted, so sending it turns the
     * request into a preflighted one — and the endpoint answers with
     * `access-control-allow-origin: *` and no `Access-Control-Allow-Headers`,
     * so the preflight is rejected and the fetch fails outright. Native has no
     * CORS and never saw it; it failed only on web, and the endpoint belongs to
     * the deployed web app, so it is not ours to relax.
     *
     * Nothing is lost. The response is `max-age=1800` and the edition changes
     * once a day, so the worst the platform cache can do is hand back a copy up
     * to half an hour old — immaterial for a daily paper, and the on-device
     * cache is what actually carries offline reading.
     */
    const response = await fetch(EDITION_URL, { signal: controller.signal });

    if (!response.ok) {
      throw new WireError(`The press returned ${response.status}`);
    }

    const edition = coerceEdition(await response.json());
    if (!edition) throw new WireError("The edition came through unreadable");
    return edition;
  } catch (error) {
    if (error instanceof WireError) throw error;
    // AbortError, DNS failure, no route to host: all the same to the reader,
    // who is simply somewhere without signal.
    throw new WireError("Could not reach the press");
  } finally {
    clearTimeout(timer);
  }
}
